#!/bin/sh

update ()
{
  src=$1;
  dest=$2;

  if `cmp -s $src $dest` ; then
   echo no change: $src $dest
  else
   echo to UPDATE: $src $dest
   cp $src $dest
  fi
}

update gc.h cord/gc.h
update cord/cord.h include/cord.h
update gc.h include/gc.h
update gc_alloc.h include/gc_alloc.h
update gc_cpp.h include/gc_cpp.h
update gc_typed.h include/gc_typed.h
update weakpointer.h include/weakpointer.h
update backptr.h include/backptr.h
update gcconfig.h include/private/gcconfig.h
update gc_priv.h include/private/gc_priv.h
update gc_hdrs.h include/private/gc_hdrs.h
