
/* libguile header for MzScheme implementation */

#ifdef _UsesMzScheme_
typedef Scheme_Object *SCM;
#else
typedef struct {} *SCM;

extern SCM scheme_true, scheme_false, scheme_null, scheme_void;
#endif

#define SCM_BOOL_T scheme_true
#define SCM_BOOL_F scheme_false
#define SCM_EOL scheme_null
#define SCM_UNSPECIFIED scheme_void

#define GH_EOL_MARKER 0L

typedef SCM (*SCM_FN)();
typedef SCM (*SCM_ARGV_FN)(int argc, SCM argv[]);
typedef void (*SCM_MAIN_FN)(int argc, char *argv[]);

#define GH_DEFER_INTS /**/
#define GH_ALLOW_INTS /**/

/* Remainder is generated by mkghsrc */

