#!/bin/sh

# Makefile-level configurations for some known platforms

if [ "${USESGCDEBUG}" = "yes" ] ; then
  GCOPTS="GCDIR='sgc' OPTIONS='-DSGC_STD_DEBUGGING=1'"
elif [ "${USESGC}" = "yes" ] ; then
  GCOPTS="GCDIR='sgc' OPTIONS='-DUSE_SENORA_GC'"
else
  GCOPTS=""
fi

OS=`uname -s`
case $OS in
  SunOS)
    case `uname -r` in
      5.*)
       if [ "${USESOLTH}" = "yes" ] ; then
	 SOLTHTFLAGS="THREADFLAGS='-DSOLARIS_THREADS'"
	 SOLTHLIBS="-lthread"
       else
	 SOLTHTFLAGS=""
	 SOLTHLIBS=""
       fi
       STATICLINK="-Wl,-Bstatic" # after -ldl
       make RANLIB=':' LIBS="-ldl -lm -lsocket -lnsl -lintl $SOLTHLIBS" $GCOPTS $SOLTHTFLAGS "$@"
       ;;
      *)
       make $GCOPTS "$@"
       ;;
    esac
    ;;
  AIX)
    if [ "${AIXUSEGCC}" = "yes" ]; then
      `which make` "$@" $GCOPTS RANLIB=':'
    else
      make "$@" $GCOPTS RANLIB=':' CC='cc' WARN='' 
    fi
    ;;
  FreeBSD)
    gmake 'CC=gcc' $GCOPTS LIBS="-lm -rdynamic" "$@"
    ;;
  OpenBSD)
    make 'PERL=' 'CC=gcc' $GCOPTS "$@"
    ;;
  IRIX)
    if [ "${USEIRIXSPROC}" = "yes" ] ; then
      IRIXTFLAGS="THREADFLAGS='-DIRIX_SPROCS'"
      IRIXTLIBS="lib/sys$MZPLATFORMSUFFIX$MZTHREADSUFFIX/sproc.o"
      IRIXGCEXTRA="GCLIBMAKEEXTRA=sproc-extra-lib"
    else
      IRIXTFLAGS=""
      IRIXTLIBS=""
      IRIXGCEXTRA=""
    fi
    STATICLINK="/usr/lib/libC.a /usr/lib/libmalloc.a"
    make SHELL=/bin/sh RANLIB=':' CC='cc' CXX='CC' AS='as' WARN='' DEBUGFLAGS='' $IRIXTFLAGS LIBS="-lm $IRIXTLIBS" $IRIXGCEXTRA "$@"
    ;;
  Linux)
    if [ "${USELINTH}" = "yes" ] ; then
       LINUXTHFLAGS='-DLINUX_THREADS -D_REENTRANT'
       LINUXTHLIBS="-lpthread"
    else
       LINUXTHFLAGS=""
       LINUXTHLIBS=""
    fi
    if [ `file /bin/ls | grep ELF | wc -l` = 1 ]; then
      make $GCOPTS LIBS="-lm -ldl -rdynamic $LINUXTHLIBS" THREADFLAGS="$LINUXTHFLAGS" "$@"
    else
      make $GCOPTS "$@"
    fi
    ;;
  OSF1)
    make $GCOPTS CC=cc NONLINKOPTIONS=-iee_with_inexact RANLIB=':' DEBUGFLAGS='' WARN='' $*
    ;;
  HP-UX)
    make CC=cc OPT=-O WARN='' OPTIONS='-Wp,-H,64000 -Aa -D_HPUX_SOURCE +k' AR='ar' LIBS='-lm -Wl,-E' DYNOPTIONS='+z' $GCOPTS DEBUGFLAGS='' "$@"
    # gcc:
    # make AR='ar' LIBS='-Wl,-E' DYNOPTIONS='-fPIC' $GCOPTS DEBUGFLAGS='' "$@"
    ;;
  SCO) # How do you really recognize SCO?
    make $GCOPTS LIBS='-lc -lsocket' RANLIB=':' "$@"
    ;;
  CYGWIN*)
    make --unix cygwin-dll-setup
    make --unix starter
    make --unix $GCOPTS PERL='' LIBS='gmzwin.exp' INSTALLTARGET=cygwin-install "$@"
    ;;
  BeOS)
    GCOPTS="GCDIR='sgc' OPTIONS='-DUSE_SENORA_GC'"
    # Use gcc if it's here
    gcc -v >& /dev/null
    if [ $? = 0 ] ; then
      COMP='CC=gcc'
    else
      COMP='CC=cc WARN=""'
    fi
    make $COMP LIBS="" $GCOPTS PERL="" "$@"
    ;;
  *)
    make $GCOPTS "$@"
    ;;
esac
