(module info (lib "infotab.ss" "setup")
  (define name "DrScheme")
  (define mred-launcher-libraries (list "drscheme.ss"))
  (define mred-launcher-names (list "DrScheme"))
  (define compile-omit-files '("drscheme.ss")))
