extern Scheme_Object *objscheme_bundle_wxItem(wxItem *);
void objscheme_setup_wxFormItem(Scheme_Env *env);
int objscheme_istype_wxFormItem(Scheme_Object *obj, const char *stop, int nullOK);
Scheme_Object *objscheme_bundle_wxFormItem(class wxFormItem *realobj);
class wxFormItem *objscheme_unbundle_wxFormItem(Scheme_Object *obj, const char *where, int nullOK);
extern wxFormItem *objscheme_unbundle_wxFormItem(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxNode(wxNode *);
extern wxPanel *objscheme_unbundle_wxPanel(Scheme_Object *, const char *, int);
extern wxFormItem *objscheme_unbundle_wxFormItem(Scheme_Object *, const char *, int);
void objscheme_setup_wxForm(Scheme_Env *env);
int objscheme_istype_wxForm(Scheme_Object *obj, const char *stop, int nullOK);
Scheme_Object *objscheme_bundle_wxForm(class wxForm *realobj);
class wxForm *objscheme_unbundle_wxForm(Scheme_Object *obj, const char *where, int nullOK);
extern wxList *objscheme_unbundle_wxList(Scheme_Object *, const char *, int);
extern wxList *objscheme_unbundle_wxList(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxFormItem(wxFormItem *);
extern wxList *objscheme_unbundle_wxList(Scheme_Object *, const char *, int);
extern Scheme_Object *objscheme_bundle_wxFormItem(wxFormItem *);
extern Scheme_Object *objscheme_bundle_wxFormItem(wxFormItem *);
extern Scheme_Object *objscheme_bundle_wxFormItem(wxFormItem *);
extern Scheme_Object *objscheme_bundle_wxFormItem(wxFormItem *);
void objscheme_setup_wxFormGlobal(Scheme_Env *env);
