
#ifdef wx_x
#define wxBITMAP_TYPE_DEFAULT (wxBITMAP_DISCARD_COLOURMAP | wxBITMAP_TYPE_XBM)
#else
#ifdef wx_msw
#define wxBITMAP_TYPE_DEFAULT (wxBITMAP_DISCARD_COLOURMAP | wxBITMAP_TYPE_BMP)
#else
#define wxBITMAP_TYPE_DEFAULT (wxBITMAP_DISCARD_COLOURMAP | wxBITMAP_TYPE_PICT)
#endif
#endif

