.\" dummy line
.TH DRSCHEME 1 "8 June 1996"
.UC 4
.SH NAME
drscheme \- The Rice PLT Scheme programming environment
.SH SYNOPSIS
.B drscheme
.SH DESCRIPTION
.I DrScheme
is Rice University's Programming Languages Group's Scheme
programming environment.
.I DrScheme
runs on a variety of platforms.
.PP
.I DrScheme
treats it's command line arguments as filenames and opens them after
starting up.
.pp
For further information on
.I DrScheme,
please consult the on-line
documentation and other information available at
.PP
.ce 1
http://www.cs.rice.edu/CS/PLT/packages/drscheme/
.SH FILES
.I DrScheme
looks for its library in the directory named by the
environment variable PLTHOME.  If this variable is not defined,
the directory /usr/local/lib/plt/ is assumed by default.
.PP
Please consult your local administrator to determine whether
the on-line documentation has been installed locally.
.SH BUGS
Email bug reports to plt-bugs@cs.rice.edu.  Please mention
"DrScheme" in the subject line or the message.
.SH AUTHOR
.I DrScheme
was implemented by Robby Findler (robby@cs.rice.edu),
Shriram Krishnamurthi (shriram@cs.rice.edu), Cormac Flanagan 
(cormac@cs.rice.edu), and Matthew Flatt (mflatt@cs.rice.edu).
.SH SEE ALSO
.BR mred(1),
.BR mzscheme(1)
