.\" dummy line
.TH DRSCHEME 1 "25 March 1998"
.UC 4
.SH NAME
drscheme \- The Rice PLT Scheme programming environment
.SH SYNOPSIS
.B drscheme
.SH DESCRIPTION
.I DrScheme
is the Rice University PLT Scheme
programming environment.
.PP
.I DrScheme
treats it's command line arguments as filenames and opens them after
starting up.
.pp
For further information on
.I DrScheme,
please consult the on-line
documentation and other information available at
.PP
.ce 1
http://www.cs.rice.edu/CS/PLT/packages/drscheme/
.SH FILES
.I DrScheme
looks for its library in the directory named by the
environment variable PLTHOME.  If this variable is not defined,
the installation directory is assumed (usually
"/usr/local/lib/plt/").
.PP
Please consult your local administrator to determine whether
the on-line documentation has been installed locally.
.SH BUGS
Submit bug reports via
.ce 1
http://www.cs.rice.edu/CS/PLT/Bugs/ (encouraged)
or by e-mail to
.ce 1
plt-bugs@cs.rice.edu (discouraged)
.SH AUTHOR
.I DrScheme
was implemented by Robby Findler (robby@cs.rice.edu),
Shriram Krishnamurthi (shriram@cs.rice.edu), Cormac Flanagan 
(cormac@cs.rice.edu), and Matthew Flatt (mflatt@cs.rice.edu).
.SH SEE ALSO
.BR mred(1),
.BR mzscheme(1)
